package co.istad.projectpracticum.phsardigital.features.pos.dto;

import jakarta.validation.Valid;
import jakarta.validation.constraints.NotEmpty;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.PositiveOrZero;
import jakarta.validation.constraints.Size;

import java.math.BigDecimal;
import java.util.List;
import java.util.UUID;

/**
 * A sale rung up at the counter.
 *
 * @param saleUuid       generated by the till, not the server. It is the sale's id and
 *                       its idempotency key, so a submission that is retried after a
 *                       dropped connection settles onto the same sale instead of
 *                       ringing it up twice
 * @param customerName   optional; a walk-in has no account
 * @param amountTendered optional cash handed over, echoed back with the change due
 * @param soldAt         optional time the sale happened, for a till that queued it
 *                       while offline. Ignored if it is in the future
 */
public record PosSaleRequest(
        @NotNull(message = "Sale UUID is required")
        UUID saleUuid,

        @NotEmpty(message = "A sale needs at least one line")
        @Size(max = 200, message = "A sale may not exceed 200 lines")
        @Valid
        List<PosSaleLineRequest> lines,

        @Size(max = 255, message = "Customer name must not exceed 255 characters")
        String customerName,

        @Size(max = 30, message = "Customer phone must not exceed 30 characters")
        String customerPhone,

        @PositiveOrZero(message = "Amount tendered cannot be negative")
        BigDecimal amountTendered,

        @Size(max = 1000, message = "Note must not exceed 1000 characters")
        String note,

        java.time.LocalDateTime soldAt
) {
}
