minio:
  url: http://localhost:9000
  access-key: admin
  secret-key: admin123
  bucket: products
spring:
  application:
    name: phsardigital
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 200MB
  datasource:
    username: ${USERNAME}
    driver-class-name: org.postgresql.Driver
    password: ${PASSWORD}
    url: ${URL}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/phsardigital
server:
  port: 8999
keycloak:
  server-url: http://localhost:8080
  realm: phsardigital
  client-id: phsardigital-admin
  client-secret: Zoom4OeVj5UAPOFfrhO9nIFKYnaCkhrA